/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
To view the source, visit: https://github.com/retypeapp/retype-for-obsidian
*/
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RetypePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/config.ts
var RETYPE_ICON_SVG = `<g fill="currentColor" transform="scale(2)"><path d="M0 0V41.7115H28.5062V0H0ZM23.388 36.5888H5.12267V5.11824H23.388V36.5888Z"/><path d="M33.135 41.7155H38.2532V9.74208L33.135 4.61938V41.7155Z"/><path d="M42.8773 14.3665V41.7157H48V19.4891L42.8773 14.3665Z"/></g>`;
var ICONS = {
  /** Custom icon name registered via addIcon() */
  retypeLogo: "retype-logo",
  /** Lucide icon for the Start button */
  play: "play",
  /** Lucide icon for the Stop button */
  stop: "square",
  /** Lucide icon for the Build button */
  build: "package",
  /** Lucide icon for the Clear log button */
  clearLog: "ban",
  /** Lucide icon for the Settings gear */
  settings: "settings",
  /** Default view icon shown in the tab header */
  viewIcon: "retype-logo"
};
var VIEW_TYPE_RETYPE_SIDEBAR = "retype-sidebar";
var COMMANDS = {
  openSidebar: {
    id: "open-sidebar",
    name: "Open panel"
  },
  startServer: {
    id: "start-server",
    name: "Start server"
  },
  stopServer: {
    id: "stop-server",
    name: "Stop server"
  }
};
var SECRET_KEY_RETYPE = "retype-key";
var DEFAULT_SETTING_VALUES = {
  autoOpenBrowser: true,
  showStatusBar: true,
  debounce: 400
};
var LABELS = {
  /** Display name shown in the panel header and view tab. */
  pluginDisplayName: "Retype",
  /** Plugin ID used for navigating to the settings tab. */
  pluginId: "retype",
  /** Retype Key setting. */
  settingKeyName: "Retype key",
  settingKeyDesc: "Your Retype Pro or Community key",
  settingKeyProUrl: "https://retype.com/pro/",
  settingKeyCommunityUrl: "https://retype.com/community/",
  settingKeyPlaceholder: "Paste key here",
  /** Auto-open browser setting. */
  settingAutoOpenName: "Open browser automatically",
  settingAutoOpenDesc: "Open the default web browser when the Retype server starts",
  /** Show status bar setting. */
  settingStatusBarName: "Show status bar item",
  settingStatusBarDesc: "Show Retype server status in the Obsidian status bar",
  /** Debounce setting. */
  settingDebounceName: "Debounce delay",
  settingDebounceDesc: "Delay in milliseconds before Retype rebuilds after a file change",
  /** Ribbon button tooltip. */
  ribbonTooltip: "Retype",
  /** Gear button tooltip. */
  gearTooltip: "Retype settings",
  /** Clear log button tooltip. */
  clearLogTooltip: "Clear output",
  /** Output panel heading. */
  outputTitle: "Output",
  /** Initial log line shown when the panel opens. */
  initialLogLine: "Click start to launch the Retype server",
  /** Project info — no project found. */
  noProjectName: "No project",
  noProjectPath: "No retype.yml found in vault",
  /** Config path click tooltip. */
  configPathTooltip: "Click to open retype.yml",
  /** Button labels. */
  startButton: "Start",
  stopButton: "Stop",
  buildButton: "Build",
  /** Install state labels. */
  step1Heading: "Step 1 \u2014 plugin installed \u2705",
  step1Message: "Add the Retype CLI to continue, see Step 2",
  step2Heading: "Step 2 \u2014 add Retype CLI",
  installButton: "Retype CLI",
  installingButton: "Installing\u2026",
  manualInstallHint: "Or, manually install by running the following command:",
  installGuideLabel: "Manual installation guide",
  installGuideUrl: "https://retype.com/guides/installation/",
  copyTooltip: "Copy to clipboard",
  copiedTooltip: "Copied!"
};
var STATUS_TEXT = {
  stopped: "Server stopped",
  starting: "Starting\u2026",
  running: "Server running",
  error: "Error"
};
var STATUS_BAR = {
  stopped: "\u2B21 Retype",
  starting: "\u2B21 Retype: Starting\u2026",
  error: "\u2B21 Retype: Error",
  /** Template — replace {host} at runtime. */
  runningTemplate: "\u2B21 Retype: {host}",
  runningFallback: "\u2B21 Retype: Running",
  titleRunning: "Retype server: {url} (click to open panel)",
  titleDefault: "Retype (click to open panel)"
};
var NOTICES = {
  cliReady: "Retype CLI found \u2713",
  cliNotFound: "Retype CLI not found. npm is not available to install it automatically. Install Retype manually \u2014 see https://retype.com/guides/getting-started/",
  installSuccess: "Retype CLI installed \u2713",
  installFailed: "Retype CLI installation failed: {message}",
  buildComplete: "Retype build completed \u2713",
  buildFailed: "Retype build failed: {message}",
  stopBeforeBuild: "Stop the Retype server before running a build"
};
var CLI_EVENTS = {
  statusChanged: "status-changed",
  urlFound: "url-found",
  log: "log",
  error: "error",
  stopped: "stopped"
};
var CLI_LOG = {
  serverStopped: "\n[Retype server stopped (exit code {code})]",
  stopping: "\n[Stopping Retype server\u2026]",
  buildComplete: "\n[Build completed \u2713]",
  buildError: "\n[ERROR] retype build exited with code {code}",
  commandPrefix: "> {cli} {args}",
  workingDir: "  Working directory: {root}",
  errorPrefix: "[ERROR] {message}",
  cliNotFound: 'Retype CLI not found at "{path}". Install it with: npm install retypeapp --global',
  processError: "Process error: {message}",
  alreadyRunning: "Server is already running. Stop it first"
};
var CSS = {
  /** Root panel container. */
  panel: "retype-panel",
  /** Header bar. */
  header: "retype-ph",
  headerBrand: "retype-ph-brand",
  headerLogo: "retype-ph-logo",
  headerName: "retype-ph-name",
  headerVersion: "retype-ph-version",
  headerGear: "retype-ph-gear",
  /** Project info section. */
  infoSection: "retype-info-section",
  projectBlock: "retype-project-block",
  projectHeader: "retype-project-header",
  projectName: "retype-project-name",
  projectNone: "retype-project-none",
  projectPath: "retype-project-path",
  projectPathLink: "retype-project-path-link",
  /** Status card. */
  statusSection: "retype-status-section",
  statusCard: "retype-status-card",
  statusRow: "retype-sc-row",
  statusDot: "retype-sc-dot",
  statusText: "retype-sc-text",
  statusUrlRow: "retype-sc-url-row",
  statusUrlText: "retype-sc-url-text",
  /** Action buttons. */
  actions: "retype-actions",
  actionsPrimary: "retype-actions-primary",
  btn: "retype-btn",
  btnStart: "retype-btn-start",
  btnStop: "retype-btn-stop",
  btnBuild: "retype-btn-build",
  /** Output log. */
  output: "retype-output",
  outputHeader: "retype-output-header",
  outputTitle: "retype-output-title",
  outputClear: "retype-output-clear",
  outputBody: "retype-output-body",
  log: "retype-log",
  logLineError: "retype-log-line-error",
  logLineWarning: "retype-log-line-warning",
  logLineUrl: "retype-log-line-url",
  logLineSuccess: "retype-log-line-success",
  /** Status bar. */
  statusBar: "retype-status-bar",
  /** Install gate UI. */
  installSection: "retype-install-section",
  installStepHeading: "retype-install-step-heading",
  installStepMessage: "retype-install-step-message",
  installBtn: "retype-install-btn",
  installBtnDisabled: "retype-install-btn-disabled",
  installCode: "retype-install-code",
  installCodeCopy: "retype-install-code-copy",
  installGuide: "retype-install-guide",
  hidden: "retype-is-hidden"
};
var URL_PATTERN = /https?:\/\/[^\s]+/;
var VERSION_PATTERN = /(\d+\.\d+[.\d]*)/;
var LOG_PATTERNS = {
  error: /error|failed/i,
  warning: /warn/i,
  url: /https?:\/\//i,
  success: /success|complete/i
};
var CONFIG_FILE_NAMES = ["retype.yml", "retype.yaml"];
var MAX_LOG_LINES = 500;
var KEY_REDACTED = "********";
var DETECTOR = {
  usingCli: "Using Retype CLI:",
  cliNotDetected: "Retype CLI not detected on system PATH",
  npmInstallCommand: "npm install retypeapp --global",
  yarnInstallCommand: "yarn global add retypeapp",
  dotnetInstallCommand: "dotnet tool install retypeapp --global",
  /** How often (ms) to poll for an externally installed CLI. */
  pollIntervalMs: 5e3
};
var INSTALL_SERVICE = {
  running: "Running: {command}\u2026",
  complete: "\nInstallation complete \u2713",
  spawnError: "[ERROR] Install failed: {message}",
  exitCode: "[ERROR] Install exited with code {code}",
  notFoundAfterInstall: "[ERROR] Installation succeeded but retype was not found on PATH after install"
};
var LEGACY_KEY_FIELD = "retypeProKey";

// src/settings.ts
var DEFAULT_SETTINGS = {
  autoOpenBrowser: DEFAULT_SETTING_VALUES.autoOpenBrowser,
  showStatusBar: DEFAULT_SETTING_VALUES.showStatusBar,
  debounce: DEFAULT_SETTING_VALUES.debounce
};
var RetypeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /** Build the settings UI. */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const keyDesc = createFragment();
    keyDesc.append("Your Retype ");
    const proLink = keyDesc.createEl("a", { text: "Pro", href: LABELS.settingKeyProUrl });
    proLink.setAttr("target", "_blank");
    keyDesc.append(" or ");
    const communityLink = keyDesc.createEl("a", { text: "Community", href: LABELS.settingKeyCommunityUrl });
    communityLink.setAttr("target", "_blank");
    keyDesc.append(" key");
    new import_obsidian.Setting(containerEl).setName(LABELS.settingKeyName).setDesc(keyDesc).addText((text) => {
      text.setPlaceholder(LABELS.settingKeyPlaceholder).setValue(this.plugin.retypeProKey).onChange((value) => {
        const trimmed = value.trim();
        this.plugin.retypeProKey = trimmed;
        void this.app.secretStorage.setSecret(
          SECRET_KEY_RETYPE,
          trimmed
        );
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName(LABELS.settingDebounceName).setDesc(LABELS.settingDebounceDesc).addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.setValue(String(this.plugin.settings.debounce));
      text.onChange((value) => {
        const parsed = parseInt(value, 10);
        if (!isNaN(parsed) && parsed >= 0) {
          this.plugin.settings.debounce = parsed;
          void this.plugin.saveSettings();
        }
      });
    });
    new import_obsidian.Setting(containerEl).setName(LABELS.settingAutoOpenName).setDesc(LABELS.settingAutoOpenDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoOpenBrowser).onChange((value) => {
        this.plugin.settings.autoOpenBrowser = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(LABELS.settingStatusBarName).setDesc(LABELS.settingStatusBarDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showStatusBar).onChange((value) => {
        this.plugin.settings.showStatusBar = value;
        void this.plugin.saveSettings();
        this.plugin.refreshStatusBar();
      })
    );
  }
};

// src/services/CliService.ts
var import_child_process2 = require("child_process");
var import_events = require("events");

// src/utils/shellEnv.ts
var import_child_process = require("child_process");
var import_os = require("os");
var _enrichedPath = null;
function getShellPath() {
  if (_enrichedPath !== null) {
    return Promise.resolve(_enrichedPath);
  }
  if (process.platform === "win32") {
    _enrichedPath = "";
    return Promise.resolve(_enrichedPath);
  }
  return new Promise((resolve) => {
    const shell = process.platform === "darwin" ? "/bin/zsh" : "/bin/bash";
    const shellEnv = {
      SHELL: shell,
      TERM: "xterm-256color",
      LANG: "en_US.UTF-8"
    };
    (0, import_child_process.execFile)(
      shell,
      ["-li", "-c", "echo $PATH"],
      { timeout: 8e3, env: shellEnv },
      (err, stdout) => {
        if (err || !stdout.trim()) {
          _enrichedPath = buildFallbackPath();
        } else {
          _enrichedPath = stdout.trim();
        }
        resolve(_enrichedPath != null ? _enrichedPath : buildFallbackPath());
      }
    );
  });
}
function enrichedEnv() {
  if (!_enrichedPath) {
    return void 0;
  }
  return {
    PATH: _enrichedPath
  };
}
function buildFallbackPath() {
  const home = (0, import_os.homedir)();
  const extras = [
    "/usr/local/bin",
    "/opt/homebrew/bin",
    "/opt/homebrew/sbin",
    `${home}/.dotnet/tools`,
    `${home}/.local/bin`
  ];
  return extras.filter(Boolean).join(":");
}

// src/services/CliService.ts
var CliService = class extends import_events.EventEmitter {
  constructor(cliPath = "retype") {
    super();
    this.process = null;
    this._status = "stopped";
    this._serverUrl = "";
    this._version = null;
    this._projectRoot = null;
    this.cliPath = cliPath;
  }
  // ── Accessors ─────────────────────────────────────────────────
  get status() {
    return this._status;
  }
  get serverUrl() {
    return this._serverUrl;
  }
  get version() {
    return this._version;
  }
  get isRunning() {
    return this._status === "running" || this._status === "starting";
  }
  // ── CLI path management ───────────────────────────────────────
  /**
   * Update the path to the Retype binary and clear the cached version.
   */
  updateCliPath(newPath) {
    this.cliPath = newPath;
    this._version = null;
  }
  // ── Installation check ────────────────────────────────────────
  /**
   * Returns `true` if the Retype CLI is reachable, `false` otherwise.
   */
  async isInstalled() {
    return new Promise((resolve) => {
      (0, import_child_process2.execFile)(
        this.cliPath,
        ["--version"],
        { timeout: 5e3, shell: process.platform === "win32", env: enrichedEnv() },
        (err) => {
          resolve(!err);
        }
      );
    });
  }
  /**
   * Returns the CLI version string (e.g. `"4.1.0"`), or `null` if not
   * installed. The result is cached after the first successful call.
   */
  async getVersion() {
    if (this._version !== null) {
      return this._version;
    }
    return new Promise((resolve) => {
      (0, import_child_process2.execFile)(
        this.cliPath,
        ["--version"],
        { timeout: 5e3, shell: process.platform === "win32", env: enrichedEnv() },
        (err, stdout) => {
          if (err) {
            resolve(null);
            return;
          }
          const match = stdout.match(VERSION_PATTERN);
          this._version = match ? match[1] : stdout.trim();
          resolve(this._version);
        }
      );
    });
  }
  // ── Server control ────────────────────────────────────────────
  /**
   * Start `retype start` in the given project root directory.
   *
   * @param projectRoot - Absolute path to the folder containing retype.yml
   * @param key         - Optional Retype license key
   * @param noOpen      - If `true`, pass `--no-open` to suppress auto-browser
   */
  async start(projectRoot, key, noOpen = true, debounce) {
    var _a, _b, _c, _d;
    if (this.isRunning) {
      this.emit(CLI_EVENTS.error, CLI_LOG.alreadyRunning);
      return;
    }
    this._status = "starting";
    this._serverUrl = "";
    this.emit(CLI_EVENTS.statusChanged, this._status);
    const args = ["start"];
    if (noOpen) {
      args.push("--no-open");
    }
    if (key) {
      args.push("--key", key);
    }
    if (debounce !== void 0) {
      args.push("--debounce", String(debounce));
    }
    const logArgs = args.map(
      (arg, index) => index > 0 && args[index - 1] === "--key" ? KEY_REDACTED : arg
    );
    this.emit(
      CLI_EVENTS.log,
      CLI_LOG.commandPrefix.replace("{cli}", "retype").replace("{args}", logArgs.join(" "))
    );
    this.emit(
      CLI_EVENTS.log,
      CLI_LOG.workingDir.replace("{root}", projectRoot)
    );
    this.emit(CLI_EVENTS.log, "");
    this._projectRoot = projectRoot;
    try {
      this.process = (0, import_child_process2.spawn)(this.cliPath, args, {
        cwd: projectRoot,
        env: enrichedEnv(),
        shell: process.platform === "win32"
      });
    } catch (err) {
      this.setError(
        CLI_LOG.processError.replace(
          "{message}",
          err.message
        )
      );
      return;
    }
    (_a = this.process.stdout) == null ? void 0 : _a.setEncoding("utf8");
    (_b = this.process.stderr) == null ? void 0 : _b.setEncoding("utf8");
    (_c = this.process.stdout) == null ? void 0 : _c.on("data", (data) => {
      this.handleOutput(data);
    });
    (_d = this.process.stderr) == null ? void 0 : _d.on("data", (data) => {
      this.handleOutput(data, true);
    });
    this.process.on("error", (err) => {
      if (err.message.includes("ENOENT")) {
        this.setError(
          CLI_LOG.cliNotFound.replace("{path}", this.cliPath)
        );
      } else {
        this.setError(
          CLI_LOG.processError.replace("{message}", err.message)
        );
      }
    });
    this.process.on("close", (code) => {
      const wasRunning = this._status !== "error";
      this.process = null;
      this._status = "stopped";
      this._serverUrl = "";
      if (wasRunning) {
        this.emit(
          CLI_EVENTS.log,
          CLI_LOG.serverStopped.replace(
            "{code}",
            String(code)
          )
        );
        this.emit(CLI_EVENTS.statusChanged, this._status);
        this.emit(CLI_EVENTS.stopped);
      }
    });
  }
  /**
   * Stop the running Retype server by spawning `retype stop` in the
   * same project directory that was passed to `start()`.
   */
  stop() {
    if (!this.isRunning) {
      return;
    }
    this.emit(CLI_EVENTS.log, CLI_LOG.stopping);
    this.execStop();
  }
  /**
   * Stop the server and wait for the process to fully exit.
   * Falls back to resolving after the timeout if the process does
   * not exit in time.
   */
  async stopAsync(timeoutMs = 5e3) {
    if (!this.isRunning) {
      return;
    }
    return new Promise((resolve) => {
      const timer = activeWindow.setTimeout(() => {
        resolve();
      }, timeoutMs);
      this.once(CLI_EVENTS.stopped, () => {
        activeWindow.clearTimeout(timer);
        resolve();
      });
      this.stop();
    });
  }
  /**
   * Spawn `retype stop` in the project root directory.
   * Output from the stop command is forwarded to the log.
   */
  execStop() {
    var _a, _b, _c, _d, _e;
    const cwd = (_a = this._projectRoot) != null ? _a : void 0;
    try {
      const stopProc = (0, import_child_process2.spawn)(this.cliPath, ["stop"], {
        cwd,
        env: enrichedEnv(),
        shell: process.platform === "win32"
      });
      (_b = stopProc.stdout) == null ? void 0 : _b.setEncoding("utf8");
      (_c = stopProc.stderr) == null ? void 0 : _c.setEncoding("utf8");
      (_d = stopProc.stdout) == null ? void 0 : _d.on("data", (data) => {
        for (const line of data.split(/\r?\n/)) {
          if (line) {
            this.emit(CLI_EVENTS.log, line);
          }
        }
      });
      (_e = stopProc.stderr) == null ? void 0 : _e.on("data", (data) => {
        for (const line of data.split(/\r?\n/)) {
          if (line) {
            this.emit(CLI_EVENTS.log, line);
          }
        }
      });
      stopProc.on("error", (err) => {
        this.emit(
          CLI_EVENTS.log,
          CLI_LOG.errorPrefix.replace("{message}", err.message)
        );
      });
    } catch (err) {
      this.emit(
        CLI_EVENTS.log,
        CLI_LOG.errorPrefix.replace(
          "{message}",
          err.message
        )
      );
    }
  }
  /**
   * Run `retype build` in the given project root directory.
   * Resolves on exit code 0, rejects with a descriptive Error otherwise.
   *
   * @param projectRoot - Absolute path to the folder containing retype.yml
   * @param key         - Optional Retype license key
   */
  build(projectRoot, key) {
    return new Promise((resolve, reject) => {
      const runBuild = () => {
        var _a, _b, _c, _d;
        const args = ["build"];
        if (key) {
          args.push("--key", key);
        }
        const logArgs = args.map(
          (arg, index) => index > 0 && args[index - 1] === "--key" ? KEY_REDACTED : arg
        );
        this.emit(
          CLI_EVENTS.log,
          CLI_LOG.commandPrefix.replace("{cli}", "retype").replace("{args}", logArgs.join(" "))
        );
        this.emit(
          CLI_EVENTS.log,
          CLI_LOG.workingDir.replace("{root}", projectRoot)
        );
        this.emit(CLI_EVENTS.log, "");
        let proc;
        try {
          proc = (0, import_child_process2.spawn)(this.cliPath, args, {
            cwd: projectRoot,
            env: enrichedEnv(),
            shell: process.platform === "win32"
          });
        } catch (err) {
          const msg = CLI_LOG.processError.replace(
            "{message}",
            err.message
          );
          this.emit(
            CLI_EVENTS.log,
            CLI_LOG.errorPrefix.replace("{message}", msg)
          );
          reject(new Error(msg));
          return;
        }
        (_a = proc.stdout) == null ? void 0 : _a.setEncoding("utf8");
        (_b = proc.stderr) == null ? void 0 : _b.setEncoding("utf8");
        const forward = (data) => data.split(/\r?\n/).filter(Boolean).forEach((l) => this.emit(CLI_EVENTS.log, l));
        (_c = proc.stdout) == null ? void 0 : _c.on("data", forward);
        (_d = proc.stderr) == null ? void 0 : _d.on("data", forward);
        proc.on("error", (err) => {
          const msg = err.message.includes("ENOENT") ? CLI_LOG.cliNotFound.replace("{path}", this.cliPath) : CLI_LOG.processError.replace(
            "{message}",
            err.message
          );
          this.emit(
            CLI_EVENTS.log,
            CLI_LOG.errorPrefix.replace("{message}", msg)
          );
          reject(new Error(msg));
        });
        proc.on("close", (code) => {
          if (code === 0) {
            this.emit(CLI_EVENTS.log, CLI_LOG.buildComplete);
            resolve();
          } else {
            const msg = CLI_LOG.buildError.replace(
              "{code}",
              String(code)
            );
            this.emit(CLI_EVENTS.log, msg);
            reject(new Error(msg));
          }
        });
      };
      runBuild();
    });
  }
  // ── Private helpers ───────────────────────────────────────────
  /**
   * Process raw output from the CLI, splitting by newline, emitting
   * log events, and detecting the server URL.
   */
  handleOutput(data, _isStderr = false) {
    const lines = data.split(/\r?\n/).filter(Boolean);
    for (const line of lines) {
      this.emit(CLI_EVENTS.log, line);
      if (this._status !== "running") {
        const urlMatch = line.match(URL_PATTERN);
        if (urlMatch) {
          const url = urlMatch[0].replace(/[.,;]+$/, "");
          this._serverUrl = url;
          this._status = "running";
          this.emit(CLI_EVENTS.statusChanged, this._status);
          this.emit(CLI_EVENTS.urlFound, url);
        }
      }
    }
  }
  /**
   * Transition to the error state and emit relevant events.
   */
  setError(message) {
    this._status = "error";
    this.process = null;
    this.emit(CLI_EVENTS.error, message);
    this.emit(CLI_EVENTS.statusChanged, this._status);
    this.emit(
      CLI_EVENTS.log,
      CLI_LOG.errorPrefix.replace("{message}", message)
    );
  }
  on(event, listener) {
    return super.on(event, listener);
  }
  once(event, listener) {
    return super.once(event, listener);
  }
};

// src/services/ProjectDetector.ts
var import_obsidian2 = require("obsidian");
var path = __toESM(require("path"));
var ProjectDetector = class {
  constructor(app) {
    this.app = app;
  }
  // ── Path helpers ──────────────────────────────────────────────
  /**
   * Return the absolute vault root path on the host filesystem.
   */
  getVaultBasePath() {
    var _a;
    const adapter = this.app.vault.adapter;
    return (_a = adapter.basePath) != null ? _a : "";
  }
  /**
   * Resolve a vault-relative path to an absolute filesystem path.
   */
  toAbsolutePath(vaultRelative) {
    return path.join(this.getVaultBasePath(), vaultRelative);
  }
  // ── Project detection ─────────────────────────────────────────
  /**
   * Find the nearest `retype.yml` walking up from the given file's
   * directory. Falls back to a root-level config. Returns `null` if
   * no config is found anywhere in the vault.
   */
  async findNearestProject(activeFile) {
    if (!activeFile) {
      return this.findRootProject();
    }
    let folder = activeFile.parent;
    while (folder) {
      for (const name of CONFIG_FILE_NAMES) {
        const configFile = this.app.vault.getAbstractFileByPath(
          (0, import_obsidian2.normalizePath)(`${folder.path}/${name}`)
        );
        if (configFile instanceof import_obsidian2.TFile) {
          return this.buildProject(configFile);
        }
      }
      folder = folder.parent;
    }
    return this.findRootProject();
  }
  // ── Private helpers ───────────────────────────────────────────
  /**
   * Look for a retype.yml / retype.yaml directly at the vault root.
   */
  async findRootProject() {
    for (const name of CONFIG_FILE_NAMES) {
      const file = this.app.vault.getAbstractFileByPath(name);
      if (file instanceof import_obsidian2.TFile) {
        return this.buildProject(file);
      }
    }
    return null;
  }
  /**
   * Build a `RetypeProject` descriptor from a retype config TFile.
   * Reads the configured site name; falls back to the folder name.
   */
  async buildProject(file) {
    var _a, _b;
    const folderPath = (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "";
    const absRoot = this.toAbsolutePath(folderPath || ".");
    let name = path.basename(absRoot);
    try {
      const content = await this.app.vault.read(file);
      const configuredName = this.getConfiguredProjectName(content);
      if (configuredName) {
        name = configuredName;
      }
    } catch (e) {
    }
    return {
      root: absRoot,
      configPath: file.path,
      name
    };
  }
  getConfiguredProjectName(content) {
    var _a;
    return (_a = this.readYamlPath(content, ["meta", "siteName"])) != null ? _a : this.readYamlPath(content, ["branding", "title"]);
  }
  readYamlPath(content, targetPath) {
    for (const entry of this.readYamlPathValues(content)) {
      if (this.pathsMatch(entry.path, targetPath)) {
        const value = this.normalizeYamlScalar(entry.value);
        if (value) {
          return value;
        }
      }
    }
    return null;
  }
  readYamlPathValues(content) {
    const values = [];
    const stack = [];
    for (const line of content.split(/\r?\n/)) {
      if (!line.trim() || line.trimStart().startsWith("#")) {
        continue;
      }
      const match = line.match(/^(\s*)([^:#][^:]*?)\s*:\s*(.*)$/);
      if (!match) {
        continue;
      }
      const indent = match[1].length;
      const key = match[2].trim().replace(/^['"]|['"]$/g, "");
      const rawValue = this.stripYamlComment(match[3].trim());
      while (stack.length > 0 && indent <= stack[stack.length - 1].indent) {
        stack.pop();
      }
      const currentPath = [...stack.map((item) => item.key), key];
      if (rawValue) {
        values.push({ path: currentPath, value: rawValue });
      } else {
        stack.push({ indent, key });
      }
    }
    return values;
  }
  pathsMatch(actualPath, targetPath) {
    const normalizedPath = actualPath.flatMap((part) => part.split("."));
    if (normalizedPath.length !== targetPath.length) {
      return false;
    }
    return normalizedPath.every((part, index) => part === targetPath[index]);
  }
  normalizeYamlScalar(value) {
    const trimmed = value.trim().replace(/^['"]|['"]$/g, "").trim();
    if (!trimmed || trimmed === "~" || trimmed.toLowerCase() === "null") {
      return null;
    }
    return trimmed;
  }
  stripYamlComment(value) {
    var _a;
    let quote = null;
    for (let index = 0; index < value.length; index += 1) {
      const char = value[index];
      if ((char === '"' || char === "'") && value[index - 1] !== "\\") {
        quote = quote === char ? null : char;
      }
      if (char === "#" && quote === null && /\s/.test((_a = value[index - 1]) != null ? _a : "")) {
        return value.slice(0, index).trim();
      }
    }
    return value;
  }
};

// src/services/CliDetector.ts
var import_child_process3 = require("child_process");
var import_events2 = require("events");
var DETECTOR_EVENTS = {
  stateChanged: "state-changed"
};
var CliDetector = class extends import_events2.EventEmitter {
  constructor() {
    super(...arguments);
    this._lastResult = { found: false };
    this._lastPmResult = null;
    this._pollTimer = null;
    this._polling = false;
  }
  /** Most recent CLI detection result. */
  get lastResult() {
    return this._lastResult;
  }
  /** Most recent package manager detection result. */
  get lastPmResult() {
    return this._lastPmResult;
  }
  // ── CLI Detection ─────────────────────────────────────────────
  /**
   * Detect whether `retype` is available on the enriched PATH.
   *
   * 1. Runs `which retype` (Unix) / `where retype` (Windows)
   * 2. If found, runs `retype -v` to confirm and get version
   *
   * Returns `{ found: true, path, version }` on success,
   * or `{ found: false }` if not available.
   */
  async detect() {
    await getShellPath();
    const binPath = await this.whichBinary("retype");
    if (!binPath) {
      this._lastResult = { found: false };
      return this._lastResult;
    }
    const version = await this.getVersion(binPath);
    if (!version) {
      this._lastResult = { found: false };
      return this._lastResult;
    }
    this._lastResult = { found: true, path: binPath, version };
    return this._lastResult;
  }
  // ── Package Manager Detection ─────────────────────────────────
  /**
   * Detect which package manager is available for installing Retype.
   * Checks npm → yarn → dotnet in priority order.
   *
   * Returns the first manager found along with the full install command.
   * If none found, returns `{ manager: null, path: null, command }` with
   * the default npm command as fallback.
   */
  async detectPackageManager() {
    await getShellPath();
    const managers = [
      { name: "npm", command: DETECTOR.npmInstallCommand },
      { name: "yarn", command: DETECTOR.yarnInstallCommand },
      { name: "dotnet", command: DETECTOR.dotnetInstallCommand }
    ];
    for (const { name, command } of managers) {
      const managerPath = await this.whichBinary(name);
      if (managerPath) {
        this._lastPmResult = { manager: name, path: managerPath, command };
        return this._lastPmResult;
      }
    }
    this._lastPmResult = {
      manager: null,
      path: null,
      command: DETECTOR.npmInstallCommand
    };
    return this._lastPmResult;
  }
  // ── Re-detection ──────────────────────────────────────────────
  /**
   * Re-run CLI detection (typically after an install completes).
   * Emits a `state-changed` event with the new result.
   */
  async redetect() {
    const result = await this.detect();
    this.emit(DETECTOR_EVENTS.stateChanged, result);
    return result;
  }
  // ── Polling ───────────────────────────────────────────────
  /** Whether the polling loop is currently active. */
  get isPolling() {
    return this._polling;
  }
  /**
   * Start polling for the CLI at the given interval.
   * Polling automatically stops once the CLI is detected.
   * Safe to call multiple times — restarts with the new interval.
   */
  startPolling(intervalMs = DETECTOR.pollIntervalMs) {
    this.stopPolling();
    this._polling = true;
    this._pollTimer = activeWindow.setInterval(() => {
      void this.pollForCli();
    }, intervalMs);
  }
  /**
   * Stop the polling loop. Safe to call even if not polling.
   */
  stopPolling() {
    if (this._pollTimer) {
      activeWindow.clearInterval(this._pollTimer);
      this._pollTimer = null;
    }
    this._polling = false;
  }
  async pollForCli() {
    const result = await this.detect();
    if (!result.found) {
      return;
    }
    await this.detectPackageManager();
    this.stopPolling();
    this.emit(DETECTOR_EVENTS.stateChanged, result);
  }
  // ── Private Helpers ───────────────────────────────────────────
  /**
   * Run `which <binary>` (Unix) or `where <binary>` (Windows) to
   * find a binary on the enriched PATH.
   */
  whichBinary(name) {
    return new Promise((resolve) => {
      const cmd = process.platform === "win32" ? "where" : "which";
      (0, import_child_process3.execFile)(
        cmd,
        [name],
        { timeout: 2e3, env: enrichedEnv() },
        (err, stdout) => {
          if (err || !stdout.trim()) {
            resolve(null);
            return;
          }
          const bin = stdout.trim().split(/\r?\n/)[0];
          resolve(bin || null);
        }
      );
    });
  }
  /**
   * Run `retype -v` to retrieve the version string.
   * Returns the trimmed first line of stdout, or `null` on failure.
   */
  getVersion(binPath) {
    return new Promise((resolve) => {
      (0, import_child_process3.execFile)(
        binPath,
        ["-v"],
        { timeout: 5e3, env: enrichedEnv() },
        (err, stdout) => {
          if (err || !stdout.trim()) {
            resolve(null);
            return;
          }
          const version = stdout.trim().split(/\r?\n/)[0].trim();
          resolve(version || null);
        }
      );
    });
  }
};

// src/services/InstallService.ts
var import_child_process4 = require("child_process");
var InstallService = class {
  constructor(detector) {
    this.detector = detector;
  }
  /**
   * Run the appropriate global install command for the given package
   * manager.
   *
   * @param manager     The package manager to use ("npm", "yarn", or "dotnet")
   * @param managerPath Absolute path to the package manager binary
   * @param onLog       Callback receiving live stdout/stderr lines
   * @returns           Result indicating success or failure
   */
  async install(manager, managerPath, onLog) {
    const args = this.getInstallArgs(manager);
    const displayCmd = `${manager} ${args.join(" ")}`;
    onLog == null ? void 0 : onLog(INSTALL_SERVICE.running.replace("{command}", displayCmd));
    return new Promise((resolve) => {
      var _a, _b;
      const child = (0, import_child_process4.spawn)(managerPath, args, {
        env: enrichedEnv(),
        stdio: ["ignore", "pipe", "pipe"]
      });
      (_a = child.stdout) == null ? void 0 : _a.on("data", (data) => {
        const lines = data.toString().split(/\r?\n/).filter(Boolean);
        for (const line of lines) {
          onLog == null ? void 0 : onLog(line);
        }
      });
      (_b = child.stderr) == null ? void 0 : _b.on("data", (data) => {
        const lines = data.toString().split(/\r?\n/).filter(Boolean);
        for (const line of lines) {
          onLog == null ? void 0 : onLog(line);
        }
      });
      child.on("error", (err) => {
        const errorMsg = INSTALL_SERVICE.spawnError.replace(
          "{message}",
          err.message
        );
        onLog == null ? void 0 : onLog(errorMsg);
        resolve({ success: false, error: errorMsg });
      });
      child.on("close", (code) => {
        this.handleInstallClose(code, onLog).then(resolve, (err) => {
          const errorMsg = INSTALL_SERVICE.spawnError.replace(
            "{message}",
            err instanceof Error ? err.message : String(err)
          );
          onLog == null ? void 0 : onLog(errorMsg);
          resolve({ success: false, error: errorMsg });
        });
      });
    });
  }
  // ── Private Helpers ───────────────────────────────────────────
  /**
   * Get the install command arguments for each supported package manager.
   */
  getInstallArgs(manager) {
    switch (manager) {
      case "npm":
        return ["install", "retypeapp", "--global"];
      case "yarn":
        return ["global", "add", "retypeapp"];
      case "dotnet":
        return ["tool", "install", "retypeapp", "--global"];
    }
  }
  async handleInstallClose(code, onLog) {
    if (code !== 0) {
      const errorMsg2 = INSTALL_SERVICE.exitCode.replace(
        "{code}",
        String(code != null ? code : "unknown")
      );
      onLog == null ? void 0 : onLog(errorMsg2);
      return { success: false, error: errorMsg2 };
    }
    onLog == null ? void 0 : onLog(INSTALL_SERVICE.complete);
    const result = await this.detector.redetect();
    if (result.found) {
      return { success: true };
    }
    const errorMsg = INSTALL_SERVICE.notFoundAfterInstall;
    onLog == null ? void 0 : onLog(errorMsg);
    return { success: false, error: errorMsg };
  }
};

// src/views/PanelView.ts
var import_obsidian3 = require("obsidian");
var RetypePanelView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin, cli, detector) {
    super(leaf);
    // State: controls which UI is rendered (install vs. ready)
    this.isCliAvailable = false;
    this.currentProject = null;
    this.logLines = [];
    this.isInstalling = false;
    // Bound event handlers (stored so they can be removed in onClose)
    this.onStatusChanged = () => {
    };
    this.onUrlFound = () => {
    };
    this.onLog = () => {
    };
    this.onError = () => {
    };
    this.onStopped = () => {
    };
    this.plugin = plugin;
    this.cli = cli;
    this.detector = detector;
  }
  /** Obsidian view type identifier. */
  getViewType() {
    return VIEW_TYPE_RETYPE_SIDEBAR;
  }
  /** Display text shown in the view tab header. */
  getDisplayText() {
    return LABELS.pluginDisplayName;
  }
  /** Lucide icon name shown in the view tab. */
  getIcon() {
    return ICONS.viewIcon;
  }
  // ── Lifecycle ─────────────────────────────────────────────────
  /** Build the panel UI, bind CLI events, and load initial data. */
  async onOpen() {
    this.isCliAvailable = this.plugin.cliDetection.found;
    this.contentEl.empty();
    this.contentEl.addClass(CSS.panel);
    this.buildHeader();
    if (this.isCliAvailable) {
      this.buildReadyState();
    } else {
      this.buildInstallState();
    }
    this.buildLogSection();
    this.bindCliEvents();
    if (this.isCliAvailable) {
      await this.refreshProjectInfo();
      await this.refreshCliVersion();
      this.syncButtonStates();
    } else {
      this.setHidden(this.outputSection, true);
    }
  }
  /** Remove CLI event listeners to prevent handler accumulation. */
  onClose() {
    this.unbindCliEvents();
    return Promise.resolve();
  }
  setHidden(element, hidden) {
    element == null ? void 0 : element.classList.toggle(CSS.hidden, hidden);
    element == null ? void 0 : element.toggleAttribute("hidden", hidden);
  }
  // ── Section Builders ──────────────────────────────────────────
  /** Branded header bar with logo, name, version badge, and gear button. */
  buildHeader() {
    const header = this.contentEl.createDiv({ cls: CSS.header });
    const brand = header.createDiv({ cls: CSS.headerBrand });
    const logoEl = brand.createSpan({ cls: CSS.headerLogo });
    (0, import_obsidian3.setIcon)(logoEl, ICONS.retypeLogo);
    brand.createSpan({ cls: CSS.headerName, text: LABELS.pluginDisplayName });
    this.cliVersionEl = brand.createSpan({ cls: CSS.headerVersion });
    this.setHidden(this.cliVersionEl, !this.isCliAvailable);
    const gearBtn = header.createEl("button", {
      cls: CSS.headerGear,
      title: LABELS.gearTooltip,
      attr: { "aria-label": LABELS.gearTooltip }
    });
    (0, import_obsidian3.setIcon)(gearBtn.createSpan(), ICONS.settings);
    gearBtn.addEventListener("click", () => {
      const a = this.app;
      a.setting.open();
      a.setting.openTabById(LABELS.pluginId);
    });
  }
  /** Project info block — name + clickable config path. */
  buildProjectInfo() {
    const section = this.contentEl.createDiv({ cls: CSS.infoSection });
    this.projectEl = section.createDiv({ cls: CSS.projectBlock });
  }
  /** Build the ready-state sections: project info, status, actions. */
  buildReadyState() {
    this.buildProjectInfo();
    this.buildStatusCard();
    this.buildActions();
  }
  /**
   * Build the install-state UI: heading, message, install button
   * (if a package manager is detected), code block with the install
   * command, and a link to the installation guide.
   */
  buildInstallState() {
    this.installSection = this.contentEl.createDiv({ cls: CSS.installSection });
    this.installSection.createDiv({
      cls: CSS.installStepHeading,
      text: LABELS.step1Heading
    });
    this.installSection.createDiv({
      cls: CSS.installStepMessage,
      text: LABELS.step1Message
    });
    this.installSection.createDiv({
      cls: CSS.installStepHeading,
      text: LABELS.step2Heading
    });
    const pm = this.plugin.pmDetection;
    if (pm && pm.manager) {
      this.installBtn = this.installSection.createEl("button", {
        cls: `${CSS.btn} ${CSS.installBtn}`
      });
      (0, import_obsidian3.setIcon)(this.installBtn.createSpan(), "circle-plus");
      this.installBtn.createSpan({ text: LABELS.installButton });
      this.installBtn.addEventListener("click", () => {
        void this.onInstallClick();
      });
      this.installSection.createDiv({
        cls: CSS.installStepMessage,
        text: LABELS.manualInstallHint
      });
      const codeBlock = this.installSection.createDiv({ cls: CSS.installCode });
      const command = pm.command;
      codeBlock.createEl("code", { text: command });
      const copyBtn = codeBlock.createEl("button", {
        cls: CSS.installCodeCopy,
        title: LABELS.copyTooltip,
        attr: { "aria-label": LABELS.copyTooltip }
      });
      (0, import_obsidian3.setIcon)(copyBtn, "copy");
      copyBtn.addEventListener("click", () => {
        void navigator.clipboard.writeText(command);
        copyBtn.title = LABELS.copiedTooltip;
        copyBtn.setAttribute("aria-label", LABELS.copiedTooltip);
        activeWindow.setTimeout(() => {
          copyBtn.title = LABELS.copyTooltip;
          copyBtn.setAttribute("aria-label", LABELS.copyTooltip);
        }, 2e3);
      });
    } else {
      this.installBtn = null;
    }
    const guideLink = this.installSection.createEl("a", {
      cls: CSS.installGuide,
      text: LABELS.installGuideLabel,
      href: LABELS.installGuideUrl
    });
    guideLink.addEventListener("click", (e) => {
      e.preventDefault();
      window.open(LABELS.installGuideUrl);
    });
  }
  /** Server status card with dot, label, and URL row. */
  buildStatusCard() {
    const section = this.contentEl.createDiv({ cls: CSS.statusSection });
    this.statusCard = section.createDiv({
      cls: `${CSS.statusCard} stopped`
    });
    const statusRow = this.statusCard.createDiv({ cls: CSS.statusRow });
    this.statusDot = statusRow.createSpan({ cls: `${CSS.statusDot} stopped` });
    this.statusText = statusRow.createSpan({
      cls: CSS.statusText,
      text: STATUS_TEXT.stopped
    });
    this.serverUrlEl = statusRow.createSpan({ cls: CSS.statusUrlRow });
    this.setHidden(this.serverUrlEl, true);
  }
  /** Start / Stop / Build action buttons. */
  buildActions() {
    const section = this.contentEl.createDiv({ cls: CSS.actions });
    const primary = section.createDiv({ cls: CSS.actionsPrimary });
    this.startBtn = primary.createEl("button", {
      cls: `${CSS.btn} ${CSS.btnStart}`
    });
    (0, import_obsidian3.setIcon)(this.startBtn.createSpan(), ICONS.play);
    this.startBtn.createSpan({ text: LABELS.startButton });
    this.startBtn.addEventListener("click", () => {
      void this.onStartClick();
    });
    this.stopBtn = primary.createEl("button", {
      cls: `${CSS.btn} ${CSS.btnStop}`
    });
    (0, import_obsidian3.setIcon)(this.stopBtn.createSpan(), ICONS.stop);
    this.stopBtn.createSpan({ text: LABELS.stopButton });
    this.stopBtn.addEventListener("click", () => this.onStopClick());
    this.setHidden(this.stopBtn, true);
    this.buildBtn = primary.createEl("button", {
      cls: `${CSS.btn} ${CSS.btnBuild}`
    });
    (0, import_obsidian3.setIcon)(this.buildBtn.createSpan(), ICONS.build);
    this.buildBtn.createSpan({ text: LABELS.buildButton });
    this.buildBtn.addEventListener("click", () => {
      void this.onBuildClick();
    });
  }
  /** Output log section with header + scrollable body. */
  buildLogSection() {
    this.outputSection = this.contentEl.createDiv({ cls: CSS.output });
    const header = this.outputSection.createDiv({ cls: CSS.outputHeader });
    header.createSpan({ cls: CSS.outputTitle, text: LABELS.outputTitle });
    const clearBtn = header.createEl("button", {
      cls: CSS.outputClear,
      title: LABELS.clearLogTooltip,
      attr: { "aria-label": LABELS.clearLogTooltip }
    });
    (0, import_obsidian3.setIcon)(clearBtn.createSpan(), ICONS.clearLog);
    clearBtn.addEventListener("click", () => this.clearLog());
    const body = this.outputSection.createDiv({ cls: CSS.outputBody });
    this.logEl = body.createDiv({ cls: CSS.log });
    const savedLines = this.logLines.length > 0 ? [...this.logLines] : this.isCliAvailable ? [LABELS.initialLogLine] : [];
    this.logLines = [];
    for (const line of savedLines) {
      this.appendLog(line);
    }
  }
  // ── CLI Event Binding ─────────────────────────────────────────
  /** Remove any previously bound CLI event listeners. */
  unbindCliEvents() {
    this.cli.removeListener(CLI_EVENTS.statusChanged, this.onStatusChanged);
    this.cli.removeListener(CLI_EVENTS.urlFound, this.onUrlFound);
    this.cli.removeListener(CLI_EVENTS.log, this.onLog);
    this.cli.removeListener(CLI_EVENTS.error, this.onError);
    this.cli.removeListener(CLI_EVENTS.stopped, this.onStopped);
  }
  bindCliEvents() {
    this.unbindCliEvents();
    this.onStatusChanged = (status) => {
      this.updateStatusUI(status);
      this.syncButtonStates();
    };
    this.onUrlFound = (url) => {
      this.showServerUrl(url);
    };
    this.onLog = (line) => {
      this.appendLog(line);
    };
    this.onError = (message) => {
      this.appendLog(`[ERROR] ${message}`, CSS.logLineError);
      new import_obsidian3.Notice(`Retype: ${message}`, 8e3);
    };
    this.onStopped = () => {
      this.setHidden(this.serverUrlEl, true);
    };
    this.cli.on(CLI_EVENTS.statusChanged, this.onStatusChanged);
    this.cli.on(CLI_EVENTS.urlFound, this.onUrlFound);
    this.cli.on(CLI_EVENTS.log, this.onLog);
    this.cli.on(CLI_EVENTS.error, this.onError);
    this.cli.on(CLI_EVENTS.stopped, this.onStopped);
  }
  // ── Button Click Handlers ─────────────────────────────────────
  /** Handle the Start button click — refresh project info and launch the CLI. */
  async onStartClick() {
    var _a, _b;
    if (this.cli.isRunning) {
      return;
    }
    await this.refreshProjectInfo();
    const root = (_b = (_a = this.currentProject) == null ? void 0 : _a.root) != null ? _b : this.app.vault.adapter.getBasePath();
    const key = this.plugin.retypeProKey || void 0;
    const noOpen = !this.plugin.settings.autoOpenBrowser;
    const debounce = this.plugin.settings.debounce;
    await this.cli.start(root, key, noOpen, debounce);
  }
  onStopClick() {
    this.cli.stop();
  }
  async onBuildClick() {
    var _a, _b;
    if (this.cli.isRunning) {
      new import_obsidian3.Notice(NOTICES.stopBeforeBuild, 4e3);
      return;
    }
    this.buildBtn.disabled = true;
    const root = (_b = (_a = this.currentProject) == null ? void 0 : _a.root) != null ? _b : this.app.vault.adapter.getBasePath();
    const key = this.plugin.retypeProKey || void 0;
    try {
      await this.cli.build(root, key);
      new import_obsidian3.Notice(NOTICES.buildComplete, 4e3);
    } catch (err) {
      new import_obsidian3.Notice(
        NOTICES.buildFailed.replace("{message}", err.message),
        8e3
      );
    } finally {
      this.buildBtn.disabled = false;
    }
  }
  // ── Install Click Handler ─────────────────────────────────────
  /**
   * Handle the "Install Retype" button click.
   * Disables the button, shows the console, streams install output,
   * and transitions to ready state on success.
   */
  async onInstallClick() {
    var _a;
    const pm = this.plugin.pmDetection;
    if (!pm || !pm.manager || !pm.path || this.isInstalling) {
      return;
    }
    this.isInstalling = true;
    if (this.installBtn) {
      this.installBtn.disabled = true;
      this.installBtn.textContent = LABELS.installingButton;
      this.installBtn.addClass(CSS.installBtnDisabled);
    }
    this.setHidden(this.outputSection, false);
    const result = await this.plugin.installService.install(
      pm.manager,
      pm.path,
      (line) => this.appendLog(line)
    );
    if (result.success) {
      this.plugin.cliDetection = this.plugin.cliDetector.lastResult;
      if (this.plugin.cliDetection.found && this.plugin.cliDetection.path) {
        this.plugin.cli.updateCliPath(this.plugin.cliDetection.path);
      }
      this.appendLog("");
      this.appendLog(LABELS.initialLogLine);
      new import_obsidian3.Notice(NOTICES.installSuccess, 4e3);
      this.transitionToReady();
    } else {
      new import_obsidian3.Notice(
        NOTICES.installFailed.replace("{message}", (_a = result.error) != null ? _a : "Unknown error"),
        8e3
      );
      if (this.installBtn) {
        this.installBtn.disabled = false;
        this.installBtn.textContent = LABELS.installButton;
        this.installBtn.removeClass(CSS.installBtnDisabled);
      }
      this.isInstalling = false;
    }
  }
  // ── State Transitions ─────────────────────────────────────────
  /**
   * Transition from install state to ready state by re-rendering.
   */
  transitionToReady() {
    this.isCliAvailable = true;
    this.isInstalling = false;
    void this.onOpen();
  }
  /**
   * Called by the plugin after CLI detection completes.
   * Updates the panel state and re-renders if needed.
   */
  async onDetectionComplete() {
    const wasAvailable = this.isCliAvailable;
    this.isCliAvailable = this.plugin.cliDetection.found;
    if (this.isCliAvailable !== wasAvailable) {
      await this.onOpen();
    } else if (this.isCliAvailable) {
      await this.refreshCliVersion();
    } else {
      await this.onOpen();
    }
  }
  // ── UI Update Helpers ─────────────────────────────────────────
  updateStatusUI(status) {
    this.statusDot.className = `${CSS.statusDot} ${status}`;
    this.statusCard.className = `${CSS.statusCard} ${status}`;
    this.statusText.textContent = STATUS_TEXT[status];
    if (status !== "running") {
      this.setHidden(this.serverUrlEl, true);
    }
  }
  syncButtonStates() {
    const running = this.cli.isRunning;
    this.setHidden(this.startBtn, running);
    this.setHidden(this.stopBtn, !running);
    this.buildBtn.disabled = running;
  }
  showServerUrl(url) {
    this.serverUrlEl.empty();
    this.setHidden(this.serverUrlEl, false);
    const link = this.serverUrlEl.createEl("a", {
      cls: CSS.statusUrlText,
      text: url,
      href: url
    });
    link.addEventListener("click", (e) => {
      e.preventDefault();
      window.open(url);
    });
  }
  /** Append a line to the output log with optional CSS class. Auto-scrolls. */
  appendLog(line, cls) {
    this.logLines.push(line);
    if (this.logLines.length > MAX_LOG_LINES) {
      this.logLines.shift();
    }
    const lineEl = this.logEl.createDiv({ text: line });
    if (cls) {
      lineEl.addClass(cls);
    } else if (LOG_PATTERNS.error.test(line)) {
      lineEl.addClass(CSS.logLineError);
    } else if (LOG_PATTERNS.warning.test(line)) {
      lineEl.addClass(CSS.logLineWarning);
    } else if (LOG_PATTERNS.url.test(line)) {
      lineEl.addClass(CSS.logLineUrl);
    } else if (LOG_PATTERNS.success.test(line)) {
      lineEl.addClass(CSS.logLineSuccess);
    }
    this.logEl.scrollTop = this.logEl.scrollHeight;
  }
  clearLog() {
    this.logLines = [];
    this.logEl.empty();
  }
  // ── Data Refresh ──────────────────────────────────────────────
  /** Refresh the project info block from the active file's nearest retype.yml. */
  async refreshProjectInfo() {
    const activeFile = this.app.workspace.getActiveFile();
    this.currentProject = await this.detector.findNearestProject(activeFile);
    this.projectEl.empty();
    if (this.currentProject) {
      const headerRow = this.projectEl.createDiv({ cls: CSS.projectHeader });
      headerRow.createDiv({
        cls: CSS.projectName,
        text: this.currentProject.name
      });
      const pathEl = headerRow.createDiv({
        cls: `${CSS.projectPath} ${CSS.projectPathLink}`,
        text: this.currentProject.configPath,
        title: LABELS.configPathTooltip
      });
      pathEl.addEventListener("click", () => {
        const file = this.app.vault.getAbstractFileByPath(
          this.currentProject.configPath
        );
        if (file instanceof import_obsidian3.TFile) {
          const leaf = this.app.workspace.getLeaf(false);
          void leaf.openFile(file);
        }
      });
    } else {
      this.projectEl.createDiv({
        cls: `${CSS.projectName} ${CSS.projectNone}`,
        text: LABELS.noProjectName
      });
      this.projectEl.createDiv({
        cls: CSS.projectPath,
        text: LABELS.noProjectPath
      });
    }
  }
  /** Query the CLI version and update the header badge. */
  async refreshCliVersion() {
    const version = await this.cli.getVersion();
    this.cliVersionEl.empty();
    if (version) {
      this.cliVersionEl.textContent = `v${version}`;
    }
  }
  // ── Public API ────────────────────────────────────────────────
  /** Called when the active file changes — refreshes project info if server is stopped. */
  async onActiveFileChange() {
    if (!this.cli.isRunning) {
      await this.refreshProjectInfo();
    }
  }
};

// src/main.ts
var RetypePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    /** Last CLI detection result — shared with the panel view. */
    this.cliDetection = { found: false };
    /** Last package manager detection result — shared with the panel view. */
    this.pmDetection = null;
    /** Retype license key — loaded from SecretStorage, held in memory only. */
    this.retypeProKey = "";
    this.statusBarItem = null;
  }
  // ── Plugin Lifecycle ──────────────────────────────────────────
  async onload() {
    await this.loadSettings();
    await this.loadRetypeKey();
    (0, import_obsidian4.addIcon)(ICONS.retypeLogo, RETYPE_ICON_SVG);
    this.cli = new CliService("retype");
    this.detector = new ProjectDetector(this.app);
    this.cliDetector = new CliDetector();
    this.installService = new InstallService(this.cliDetector);
    this.cliDetector.on(DETECTOR_EVENTS.stateChanged, (result) => {
      var _a;
      this.cliDetection = result;
      this.pmDetection = this.cliDetector.lastPmResult;
      if (result.found && result.path) {
        this.cli.updateCliPath(result.path);
        console.debug(DETECTOR.usingCli, result.path);
      }
      void ((_a = this.getSidebarView()) == null ? void 0 : _a.onDetectionComplete());
    });
    this.registerView(VIEW_TYPE_RETYPE_SIDEBAR, (leaf) => {
      return new RetypePanelView(
        leaf,
        this,
        this.cli,
        this.detector
      );
    });
    this.addRibbonIcon(ICONS.retypeLogo, LABELS.ribbonTooltip, () => {
      void this.activateSidebar();
    });
    if (this.settings.showStatusBar) {
      this.initStatusBar();
    }
    this.cli.on(CLI_EVENTS.statusChanged, () => this.updateStatusBar());
    this.cli.on(CLI_EVENTS.urlFound, () => this.updateStatusBar());
    this.addCommand({
      id: COMMANDS.openSidebar.id,
      name: COMMANDS.openSidebar.name,
      callback: () => {
        void this.activateSidebar();
      }
    });
    this.addCommand({
      id: COMMANDS.startServer.id,
      name: COMMANDS.startServer.name,
      callback: () => {
        void this.startServerFromCommand();
      }
    });
    this.addCommand({
      id: COMMANDS.stopServer.id,
      name: COMMANDS.stopServer.name,
      callback: () => this.cli.stop()
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        var _a;
        void ((_a = this.getSidebarView()) == null ? void 0 : _a.onActiveFileChange());
      })
    );
    this.addSettingTab(new RetypeSettingTab(this.app, this));
    void this.detectCli();
  }
  onunload() {
    var _a, _b;
    (_a = this.cliDetector) == null ? void 0 : _a.stopPolling();
    if ((_b = this.cli) == null ? void 0 : _b.isRunning) {
      void this.cli.stopAsync(1500);
    }
  }
  // ── Settings ──────────────────────────────────────────────────
  /** Load persisted settings from data.json, merging with defaults. */
  async loadSettings() {
    const stored = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, stored != null ? stored : {});
  }
  /** Persist settings to data.json. */
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ── Secret Storage ────────────────────────────────────────────
  /**
   * Load the Retype key from Obsidian's SecretStorage.
   * If a legacy `retypeProKey` field exists in data.json, migrate it.
   */
  async loadRetypeKey() {
    const secret = this.app.secretStorage.getSecret(SECRET_KEY_RETYPE);
    if (secret) {
      this.retypeProKey = secret;
    }
    const raw = await this.loadData();
    if (raw && typeof raw[LEGACY_KEY_FIELD] === "string" && raw[LEGACY_KEY_FIELD]) {
      const legacyKey = raw[LEGACY_KEY_FIELD];
      if (!this.retypeProKey) {
        this.retypeProKey = legacyKey;
        this.app.secretStorage.setSecret(
          SECRET_KEY_RETYPE,
          legacyKey
        );
      }
      delete raw[LEGACY_KEY_FIELD];
      await this.saveData(raw);
    }
  }
  async startServerFromCommand() {
    var _a;
    await this.activateSidebar();
    await ((_a = this.getSidebarView()) == null ? void 0 : _a.onStartClick());
  }
  getSidebarView() {
    const [leaf] = this.app.workspace.getLeavesOfType(VIEW_TYPE_RETYPE_SIDEBAR);
    return (leaf == null ? void 0 : leaf.view) instanceof RetypePanelView ? leaf.view : null;
  }
  // ── Sidebar Management ────────────────────────────────────────
  /** Reveal the existing Retype sidebar or open a new one. */
  async activateSidebar() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_RETYPE_SIDEBAR);
    if (existing.length > 0) {
      await workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_RETYPE_SIDEBAR,
        active: true
      });
      await workspace.revealLeaf(leaf);
    }
  }
  /** Check whether the sidebar panel is currently visible. */
  isSidebarOpen() {
    return this.app.workspace.getLeavesOfType(VIEW_TYPE_RETYPE_SIDEBAR).length > 0;
  }
  /** Close all Retype sidebar leaves. */
  closeSidebar() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_RETYPE_SIDEBAR).forEach((leaf) => leaf.detach());
  }
  // ── Status Bar ────────────────────────────────────────────────
  /** Create the status bar item and wire the click handler. */
  initStatusBar() {
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass(CSS.statusBar);
    this.statusBarItem.addEventListener("click", () => {
      var _a, _b;
      const url = (_a = this.cli) == null ? void 0 : _a.serverUrl;
      if (((_b = this.cli) == null ? void 0 : _b.status) === "running" && url) {
        window.open(url);
      } else if (this.isSidebarOpen()) {
        this.closeSidebar();
      } else {
        void this.activateSidebar();
      }
    });
    this.updateStatusBar();
  }
  /** Set the status bar text based on current CLI state. */
  updateStatusBar() {
    var _a, _b, _c;
    if (!this.statusBarItem) {
      return;
    }
    const status = (_b = (_a = this.cli) == null ? void 0 : _a.status) != null ? _b : "stopped";
    const url = (_c = this.cli) == null ? void 0 : _c.serverUrl;
    let text;
    switch (status) {
      case "running": {
        if (url) {
          try {
            text = STATUS_BAR.runningTemplate.replace(
              "{host}",
              new URL(url).host
            );
          } catch (e) {
            text = STATUS_BAR.runningFallback;
          }
        } else {
          text = STATUS_BAR.runningFallback;
        }
        break;
      }
      case "starting":
        text = STATUS_BAR.starting;
        break;
      case "error":
        text = STATUS_BAR.error;
        break;
      default:
        text = STATUS_BAR.stopped;
    }
    this.statusBarItem.textContent = text;
    this.statusBarItem.title = status === "running" && url ? STATUS_BAR.titleRunning.replace("{url}", url) : STATUS_BAR.titleDefault;
  }
  /** Create or remove the status bar item to match the current setting. */
  refreshStatusBar() {
    if (this.settings.showStatusBar && !this.statusBarItem) {
      this.initStatusBar();
    } else if (!this.settings.showStatusBar && this.statusBarItem) {
      this.statusBarItem.remove();
      this.statusBarItem = null;
    }
  }
  // ── Plugin Directory ──────────────────────────────────────────
  /** Absolute filesystem path to this plugin's install directory. */
  getPluginDir() {
    var _a;
    const adapter = this.app.vault.adapter;
    return adapter.getFullPath((_a = this.manifest.dir) != null ? _a : "");
  }
  // ── CLI Detection ─────────────────────────────────────────────
  /**
   * Detect whether the Retype CLI is available on the system PATH.
   * Also detects available package managers. Results are stored on the
   * plugin instance and shared with the panel view.
   *
   * Never blocks plugin startup — runs asynchronously.
   */
  async detectCli() {
    var _a;
    this.cliDetection = await this.cliDetector.detect();
    this.pmDetection = await this.cliDetector.detectPackageManager();
    if (this.cliDetection.found && this.cliDetection.path) {
      this.cli.updateCliPath(this.cliDetection.path);
      console.debug(DETECTOR.usingCli, this.cliDetection.path);
    } else {
      console.debug(DETECTOR.cliNotDetected);
      this.cliDetector.startPolling();
    }
    void ((_a = this.getSidebarView()) == null ? void 0 : _a.onDetectionComplete());
  }
};

/* nosourcemap */